#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${SCRIPT_DIR}/../src/main/resources/map

wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Lookout.png?mn=1\&mt=1
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Beach.png?mn=1\&mt=1
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Graveyard.png?mn=1\&mt=1
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Dungeon.png?mn=1\&mt=1
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Alleyways.png?mn=1\&mt=2
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Pen.png?mn=1\&mt=2
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Desert.png?mn=1\&mt=2
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/AridLake.png?mn=1\&mt=2
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cavern.png?mn=1\&mt=2
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Marshes.png?mn=1\&mt=2
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Iceberg.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cage.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Springs.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Excavation.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SulphurWastes.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DryPeninsula.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Quay.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/BurialChambers.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cells.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arcade.png?mn=1\&mt=3
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CitySquare.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Antiquary.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Courthouse.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Strand.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Chateau.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Grotto.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Gorge.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Volcano.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Beacon.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Canyon.png?mn=1\&mt=4
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Baths.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Corrosion.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Chambers.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Maze.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Channel.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Sewer.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/VaalCity.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/IvoryTemple.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SpiderLair.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Barrows.png?mn=1\&mt=5
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Mausoleum.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Fields.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/JungleValley.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Phantasmagoria.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Academy.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Thicket.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Wharf.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DryWoods.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Atoll.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cemetery.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/UndergroundSea.png?mn=1\&mt=6
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Tribunal.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CorpseTrench.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Crematorium.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Residence.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Ramparts.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Dunes.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Catacomb.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/UndergroundRiver.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Terrace.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/ArachnidNest.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Bazaar.png?mn=1\&mt=7
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Laboratory.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Infestation.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/OvergrownRuin.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/VaalPyramid.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Quarry.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Armory.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Courtyard.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/MudGeyser.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Shore.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/TropicalIsland.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/MineralPools.png?mn=1\&mt=8
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/LunarisTemple.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Sepulchre.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Tower.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/WastePool.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Plateau.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Estuary.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Vault.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Temple.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arena.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Museum.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Scriptorium.png?mn=1\&mt=9
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Boulevard.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Shipyard.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Belfry.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arachnid.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Wasteland.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Precinct.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Bog.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Pier.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Crypt.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Orchard.png?mn=1\&mt=10
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Promenade.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Lair.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Colonnade.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/PrimordialPool.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SpiderForest.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Coves.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Waterways.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Factory.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Mesa.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Pit1.png?mn=1\&mt=11
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DefiledCathedral.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Summit.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/OvergrownShrine.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CastleRuins.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CrystalOre.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Villa.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/TortureChamber.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Necropolis.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Racecourse.png?mn=1\&mt=12
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Abyss.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Ghetto.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Park.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Malformation.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/HighGardens.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Shrine.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arsenal.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Oasis.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Core.png?mn=1\&mt=13
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Colosseum.png?mn=1\&mt=14
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/AcidLakes.png?mn=1\&mt=14
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DarkForest.png?mn=1\&mt=14
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Sanctuary.png?mn=1\&mt=14
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Plaza.png?mn=1\&mt=14
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Dig.png?mn=1\&mt=14
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Palace.png?mn=1\&mt=14
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Corpse.png?mn=1\&mt=15
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Basilica.png?mn=1\&mt=15
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SunkenCity.png?mn=1\&mt=15
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Reef.png?mn=1\&mt=15
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Carcass.png?mn=1\&mt=15
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/Chimera.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/Hydra.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/Minotaur.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/Phoenix.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/VaalTemple3.png

wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/musicbox.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/WolfMap.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/DeathandTaxes.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/HallOfGrandmasters.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/HallowedGround.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/MaelstromofChaos.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/FairgravesMap01.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/oba.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/olmec.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/PillarsOfVastiri.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/PoorjoysAsylum.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/UndeadSiege.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/PerandusManor.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/PutridCloister.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/Celestial.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/TheVinktarSquare.png
wget wget --content-disposition http://web.poecdn.com/image/Art/2DItems/Maps/UniqueMapEye.png