#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ${SCRIPT_DIR}/../src/main/resources/essence

# https://poecraft.com/essence
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Greed1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Greed2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Greed3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Greed4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Greed5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Greed6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Greed7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Contempt1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Contempt2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Contempt3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Contempt4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Contempt5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Contempt6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Contempt7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Hatred1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Hatred2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Hatred3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Hatred4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Hatred5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Hatred6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Hatred7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Woe1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Woe2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Woe3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Woe4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Woe5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Woe6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Woe7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Fear2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Fear3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Fear4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Fear5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Fear6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Fear7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anger2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anger3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anger4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anger5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anger6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anger7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Torment2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Torment3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Torment4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Torment5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Torment6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Sorrow2.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Sorrow3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Sorrow4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Sorrow5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Sorrow6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Sorrow7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Rage3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Rage4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Rage5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Rage6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Rage7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Suffering3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Suffering4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Suffering5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Suffering6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Suffering7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Wrath3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Wrath4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Wrath5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Wrath6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Wrath7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Doubt3.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Doubt4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Doubt5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Doubt6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Doubt7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Loathing4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Loathing5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Loathing6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Loathing7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Zeal4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Zeal5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Zeal6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Zeal7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anguish4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anguish5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anguish6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Anguish7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Spite4.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Spite5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Spite6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Spite7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Scorn5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Scorn6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Scorn7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Envy5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Envy6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Envy7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Misery5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Misery6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Misery7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Dread5.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Dread6.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Dread7.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Insanity1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Horror1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Madness1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/Terror1.png
wget http://web.poecdn.com/image/Art/2DItems/Currency/Essence/EssenceCorrupt.png
